### PR TITLE
fix: tests with strings and objects in type array

### PR DESCRIPTION
**Pull request by frk-dc**
### Change
One test to be deleted (`array_array_union_complex`) and one to be amended (`optional_array`)

### Rationale
The tests mix string and objects within the `type` array, but type supports only string values.

### Sources
https://json-schema.org/understanding-json-schema/reference/type.html#type
> The type keyword may either be a string or an array:
>  - If it’s a string, it is the name of one of the basic types above.
>  - If it is an array, it must be an array of strings, where each string is the name of one of the basic types, and each element is unique. In this case, the JSON snippet is valid if it matches any of the given types.

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/json-schema/index.d.ts#L634

### CODE REVIEW

**Comment by frk-dc** [comment]
@thedumbterminal just pinging to ask if you've had any chance to check this and https://github.com/thedumbterminal/jsonschema-avro/pull/109

**Comment by thedumbterminal** [comment]
Thanks for this, I can see the error in the input schemas, but I think we should fix the test input schema so a multiple type array is still given and see how the code copes with this.

**Comment by frk-dc** [comment]
>we should fix the test input schema so a multiple type array is still given

[array_array_complex](https://github.com/thedumbterminal/jsonschema-avro/blob/master/test/integration/samples/array_array_complex/input.json#L21) and other tests already include multiple-type arrays.
Unless I'm missing something, it appears that the point of the deleted "union complex" tests was to mix strings and objects inside type array.
If we replace the objects with string values, wouldn't the tests become redundant?

**Comment by frk-dc** [comment]
@thedumbterminal any news on this PR and the [TS conversion](https://github.com/thedumbterminal/jsonschema-avro/pull/109)?

**Pull request merged**
